// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0GAVgq4JWhR__JX_wr1YI5uo_a67KmE',
    appId: '1:636220244656:web:acdf3b4823d45b640bf175',
    messagingSenderId: '636220244656',
    projectId: 'aellpr-9026e',
    authDomain: 'aellpr-9026e.firebaseapp.com',
    storageBucket: 'aellpr-9026e.appspot.com',
    measurementId: 'G-Y498MZM5J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9EYwpdorSXqaZDIh4IamLYSyEK_TSFeY',
    appId: '1:636220244656:android:b3fe971f76fb81540bf175',
    messagingSenderId: '636220244656',
    projectId: 'aellpr-9026e',
    storageBucket: 'aellpr-9026e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2XNNjo8mZTz7pjITcUNuVde2uVZDawws',
    appId: '1:636220244656:ios:29f636c577dfb82a0bf175',
    messagingSenderId: '636220244656',
    projectId: 'aellpr-9026e',
    storageBucket: 'aellpr-9026e.appspot.com',
    iosBundleId: 'com.example.aellpr',
  );
}
